spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=order_management;encrypt=true;trustServerCertificate=true
    username: sa
    password: songlong
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect